const categoryList = [
  "Nature",
  "Film",
  "Travel",
  "Food & Drink",
  "Technology",
  "Fashion",
  "Sports",
  "Science",
  "Health & Wellness",
  "Personal Growth",
  "Home Decor",
  "Relationships",
  "Literature",
  "Gaming",
  "Art & Photography",
  "Education",
  "Business & Finance",
  "Sustainability",
  "Hobbies & Crafts",
  "Society & Culture",
  "Life Hacks & Tips",
];

export default categoryList;
