const textConfig = {
  title: "Blog Space",
  subtitle: "Your Space for Endless Stories.",
  navMenu: {
    home: "Home",
    myblog: "My Blogs",
    category: "Categories",
    auth: "Login | Signup",
  },
  dashboard: {
    title: ["From", "Thoughts", "To", "Words", "..."],
    subtitle: "Where Ideas come to Life.",
    tag: [
      "Discover a world of insights, stories, and knowledge. Start writing your own",
      "journey",
      "today.",
    ],
    dayBlog: "Blog of the Day",
    latest: "Latest Blogs",
    article: "Trending Articles",
    all: "All Posts",
  },
  auth: {
    login: "Log In",
    signup: "Sign Up",
    login2: "Login Now ...",
    fgtpwd: "Forgot your password?",
    fgtpwd2: "Trouble logging in?",
    create: "Create Account",
    tag1: "Hello, Friend!",
    tag2: "Already have a account? Your Creative Space Awaits. Get started ..",
    tag3: "Welcome Back!",
    tag4: "Dont have an account? Connect with us and share your stories ..",
    resetemail: "Enter your registered email to get back on track.",
    continue: "Continue",
    resend: "Resend Email",
    inbox: "Check your Inbox",
    check: "Didn't receive the email? check spam folder or",
    reset: "Reset Password",
    createPwd: "Create New Password",
    newPwd: "New Password",
    cnfPwd: "Confirm Password",
    success: "Password Reset Successful",
    note: "Password security begins with a strong password: at least 10 characters, including uppercase letters, lowercase letters, numbers, and symbols.",
    verifying: "Verifying your account ...",
    verify: "Feature Locked: Verify your account to unlock this action.",
    verified: "Email Verified",
    verified2: "Your account is now verified. Proceed to Login.",
  },
  user: {
    save: "Save",
    upload: "Upload",
    saved: "Profile Information successfully updated",
    saving: "Saving your changes",
    total: "Total Posts",
    addPost: "Add a New Post",
    delete: "Delete Post ?",
    edit: "Edit Post",
    deleteErr: "Error deleting the post. Try again later.",
    deleteScs: "Post Successfully Deleted",
    redirect: "Redirecting you to your profile . . .",
  },
  shared: {
    more: "Read More",
  },
  related: "Related Posts",
  view: "View All",
  read: "Read Article ...",
  by: "By",
  allcategory: "All Categories",
  postEdit: {
    title: "Post Title :",
    content: "Post Content :",
    category: "Post Category :",
    img: "Featured Image :",
    status: "Post Status :",
    format: "Unsupported file format! Select valid image",
    save: "Save Post",
    option: "select option",
    other: "Other :",
    saveSuccess: "Post saved successfully. Taking you to your post.",
    success: "Redirecting ...",
  },
  banner: {
    line1: '"Why just read when you can write?',
    line2: 'now to share your own stories"',
  },
  loaders: {
    dataload: "Loading Blog Information ...",
    authenticate: "Authenticating ...",
    userpost: "Curating your personal collection ... ",
    edit: "Hang On, Retrieving Your Work ...",
    category: "Gathering categories . . . Just a moment.",
  },
  errs: {
    profile: "Something went wrong. Please try later!",
  },
};

export default textConfig;
